config/routes.rb
Qanda::Application.routes.draw do
  devise_for :users

  resources :questions do
    resources :answers, :only => :create
  end

  match 'votes/up/:answer_id' => 'votes#up', :via => :post, :as => :vote_up
  match 'votes/down/:answer_id' => 'votes#down', :via => :post, :as => :vote_down

  root :to => "questions#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all
    elsif user.role == 'moderator'
      can :manage, Question
    elsif user.role == 'user'
      can [:create, :read], Question
      can [:create, :read], Answer
      can :create, Vote
      can :manage, Question, :user_id => user.id
    else
      can :read, [Question, Answer]
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :votes

  def update_score
    self.score = Vote.where( :answer_id => self.id ).sum( 'vote' )
    self.save
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, :order => 'score DESC'
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, 
    :password_confirmation, :remember_me,
    :username, :role, :photo

  ROLES = ['admin', 'moderator', 'user']

  has_attached_file :photo

  has_many :questions
  has_many :answers
  has_many :votes

  has_many :answered_questions, :through => :answers, :source => :question
  has_many :voted_answers, :through => :votes, :source => :answer
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user

#  validates :user_id, :uniqueness => { :scope => :answer_id }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(params[:answer])
    @answer.user = current_user
    @answer.save
    redirect_to question_path(@question)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "Access denied."
    redirect_to root_url
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  authorize_resource

  # GET /questions
  # GET /questions.xml
  def index
    @search = Question.search params[:search]
    @questions = @search.paginate :include => [:answers, :user], :page => params[:page], :per_page => 5

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])
    @question.user_id = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def up
    create_vote( 1, params[:answer_id], current_user)
  end

  def down
    create_vote(-1, params[:answer_id], current_user)
  end

  private

  def create_vote(vote, answer, user)
    @answer = Answer.find answer

    @vote = @answer.votes.create :user_id => user, :vote => vote

    @answer.update_score
    redirect_to question_path(@answer.question)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qanda</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <% if user_signed_in? %>
    <%= link_to "Profile", edit_user_registration_path %> |
    <%= link_to "Sign out", destroy_user_session_path,
      :method => :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %> |
    <%= link_to "Sign up", new_user_registration_path %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= link_to root_path do %>
    <h1>Questions and Answers</h1>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h2>Edit question</h2>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<%= form_for @search do |f| %>
  <p>
    <%= f.text_field :body_contains %>
    <%= f.submit 'Search' %>
  </p>
<% end %>

<% if can? :create, Question %>
  <%= link_to 'New Question', new_question_path %>
<% end %>

<% @questions.each do |question| %>
  <p><%= question.body %></p>
  <p><i>By <%= question.user.email %></i></p>
  <p><%= pluralize question.answers.length, 'answer' %></p>

  <p>
    <%= link_to 'Show', question %>
    <% if can? :manage, question %>
      | <%= link_to 'Edit', edit_question_path(question) %>
      | <%= link_to 'Destroy', question, 
            :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
  </p>

  <br />
<% end %>

<%= will_paginate @questions %>

app/views/questions/new.html.erb
<h2>New question</h2>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p><%= @question.body %></p>
<p>By <%= @question.user.email %></p>

<p>
  <%= link_to 'Edit', edit_question_path(@question) %> |
  <%= link_to 'Back', questions_path %>
</p>

<h3>Answers</h3>

<% @question.answers.each do |answer| %>
  <blockquote>
    <p><%= answer.body %></p>
    <p><i>By <%= answer.user.email %></i></p>
    <p>Score: <%= answer.score %></p>
    <% if can? :create, Vote %>
      <%= button_to 'Vote Up', vote_up_path(answer) %>
      <%= button_to 'Vote Down', vote_down_path(answer) %>
    <% end %>
  </blockquote>
  <br />
<% end %>

<% if can? :create, Answer %>
  <h3>Add Your Answer</h3>
  <%= form_for([@question, @question.answers.build]) do |f| %>
    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %> 
<% end %>